development:
  adapter: postgresql 
  encoding: utf8
  database: levelbar_development
  min_messages: warning

test:
  adapter: postgresql 
  encoding: utf8
  min_messages: warning
  database: levelbar_test

production:
  adapter: postgresql 
  encoding: utf8
  min_messages: warning
  database: levelbar_production
